[package]
name = "metaflac"
version = "0.0.1"
authors = ["James Hurst <jamesrhurst@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jamesrhurst/rust-metaflac"
repository = "https://github.com/jamesrhurst/rust-metaflac"
documentation = "https://jamesrhurst.github.io/rust-metaflac"
description = "A library for reading and writing FLAC metadata."

[dependencies]
libc = "*"
log = "*"
rustc-serialize = "*"
byteorder = "*"
num = "*"
