[package]
name = "metaflac"
version = "0.1.4"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jameshurst/rust-metaflac"
repository = "https://github.com/jameshurst/rust-metaflac"
documentation = "https://jameshurst.github.io/rust-metaflac"
description = "A library for reading and writing FLAC metadata."

[dependencies]
log = "0.3.6"
rustc-serialize = "0.3.19"
byteorder = "0.5.1"
num = "0.1.32"
