[package]
name = "metaflac"
version = "0.0.1"
authors = ["James Hurst <jamesrhurst@users.noreply.github.com>"]

[dependencies]
log = "*"
rustc-serialize = "*"

[dependencies.audiotag]
git = "https://github.com/jamesrhurst/rust-audiotag.git"
